### ISSUE TITLE
Module Errors When Updating constructorio-node Version

### ISSUE THREAD

**Issue by angelam9** [Constructor-io/constructorio-node#152]
We recently updated our constructorio-node version from 3.10.3 to 4.5.3. This has produced `Module not found` errors on compilation:

<img width="905" alt="Screen Shot 2023-05-10 at 2 44 12 PM" src="https://github.com/Constructor-io/constructorio-node/assets/33735783/c4f75dd8-3f90-48fe-a6a1-d7fc89f900a7">

<br>
<br>

Both of these modules being requested come from constructorio-node:
<img width="345" alt="Screen Shot 2023-05-10 at 2 45 52 PM" src="https://github.com/Constructor-io/constructorio-node/assets/33735783/afdb5f58-a656-492b-9cf5-f739cf917077">
<img width="345" alt="Screen Shot 2023-05-10 at 2 46 16 PM" src="https://github.com/Constructor-io/constructorio-node/assets/33735783/a581835d-6c07-4608-a49a-02ec71f4e046">

Can we get a fix for these errors?

**Comment by esezen** [comment]
Hello @angelam9, thanks for reporting this. We are looking into this issue and will update you shortly. Would you be able to share the Node version you are using?

**Comment by angelam9** [comment]
@esezen We are using node version 16.14.2.

**Comment by esezen** [comment]
Resolved
