### ISSUE TITLE
Unable to use recommendations params types

### ISSUE THREAD

**Issue by tomdickman** [Constructor-io/constructorio-node#174]
The `RecommendationsParameters` interface is not exported, this makes it difficult to construct dynamic and type safe params to pass into the `getRecommendations` method without having to declare a new type with the same structure as this interface or typecasting

https://github.com/Constructor-io/constructorio-node/blob/95730bcc3e3fe370b93fe033e979462a463cfc85/src/types/recommendations.d.ts#L5

**Comment by esezen** [comment]
@tomdickman thanks for raising this. The type has been exported in the latest version
