### ISSUE TITLE
groups_start type doesn't support group_id:{id}

### ISSUE THREAD

**Issue by CatchGus** [Constructor-io/constructorio-node#200]
Are you able to please update the `FmtOptions` interface to support `group_id:{id}` under the `groups_start` field as per the documentation? https://docs-beta.constructor.io/reference/v1-search-get-search-results

https://github.com/Constructor-io/constructorio-node/blob/master/src/types/index.d.ts#L36
```
export interface FmtOptions extends Record<string, any> {
  groups_max_depth?: number;
  groups_start?: 'current' | 'top' | `group_id:${string}`;
}
```

**Comment by mocca102** [comment]
Thanks for raising that @CatchGus we will add the updates and let you know

**Comment by mocca102** [comment]
This has been updated [here](https://github.com/Constructor-io/constructorio-node/pull/201) @CatchGus 
I will close the issue
